name: CI
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - '*'
jobs:
  build_and_tests_on_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          pip install coverage tensorflow
          pip install -e ./
      - name: Unit testing
        run: |
          python -m unittest discover -v
          datum -h
      - name: Code instrumentation
        run: |
          coverage run -m unittest discover -v
          coverage run -a datum.py -h
          coverage xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-reports: coverage.xml
      # - name: Sending coverage results
      #   env:
      #     COVERALLS_SERVICE_NAME: github
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     coveralls
