name: CI
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - '*'
jobs:
  build_and_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
      - run: |
          pip install coverage tensorflow
          pip install -e ./
      - name: Measuring code coverage
        run: |
          coverage run -m unittest discover -v
          coverage run -a datum.py -h
          coverage xml
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
      - name: Unit testing
        run: |
          python -m unittest discover -v
          datum -h
