name: CI_pull_request
on: pull_request
jobs:
  build_and_tests_on_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          pip install coverage tensorflow
          pip install -e ./
      - name: Unit testing
        run: |
          python -m unittest discover -v
          datum -h
