name: Linter
on: pull_request
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run checks
        run: |
          pip install --user -r <(grep "^pylint" ./requirements.txt)
          echo "Pylint version: "`pylint --version | head -1`
          git ls-files -z '*.py' | xargs -0 pylint -r n
