name: Linter
on: pull_request
jobs:
  Remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 12

      - name: Run checks
        run: |
          npm ci
          echo "Remark version: "`npx remark --version`
          npx remark --frail .
